--insert into usuario (id, nome, email) values (1, 'Messi', 'messi@email.com');
--insert into usuario (id, nome, email) values (2, 'Neymar', 'neymar@email.com');
--insert into usuario (id, nome, email) values (3, 'Cristiano', 'cristiano@email.com');